#importar turtle a python
import turtle
#importar textwrap
import textwrap

# Pedir el nombre del nino

def pedir_nombre():
    while True:
        nombre = input("Por favor, ingresa tu nombre: ")
        if nombre.strip():  # Verifica que el nombre no esté vacío
            return nombre
        else:
            print("El nombre no puede estar vacío. Por favor, inténtalo de nuevo.")

# Pedir la edad del nino
def pedir_edad():
    while True:
        edad = input("Por favor, ingresa tu edad: ")
        if edad.isdigit():  # Verifica que la edad sea un número entero
            return int(edad)
        else:
            print("La edad debe ser un número entero. Por favor, inténtalo de nuevo.")

# Pedir los colores favoritos, en forma de listado 

def pedir_color():
    colores_disponibles = {"rojo": "#FF0000", "azul": "#0000FF", "verde": "#00FF00", "negro": "#000000", "rosado": "#FFC0CB"}
    while True:
        print("Elige tu color favorito:")
        for i, color in enumerate(colores_disponibles.keys(), start=1):
            print(f"{i}. {color}")
        opcion = input("Ingresa el número correspondiente a tu color favorito: ")
        if opcion.isdigit() and 1 <= int(opcion) <= len(colores_disponibles):
            seleccion = list(colores_disponibles.keys())[int(opcion) - 1]
            return colores_disponibles[seleccion]
        else:
            print("Opción inválida. Por favor, elige un número válido.")
# Codigos de color 

# Función para dibujar el panel con el título y los espacios
def dibujar_panel(titulo, narrativa, dibujo_panel,color):

    # Configuración inicial
    panel = turtle.Screen()
    panel.setup(width=600, height=400)
    panel.title(titulo)
    panel.bgcolor("lightgray")

    # Dibujar el título
    titulo_turtle = turtle.Turtle()
    titulo_turtle.penup()
    titulo_turtle.goto(0, 275)
    titulo_turtle.write(titulo, align="center", font=("Arial", 20, "bold"))
    titulo_turtle.hideturtle()

    # Dividir la narrativa en varias líneas
    lineas_narrativa = textwrap.wrap(narrativa, width=60)

    # Dibujar la narrativa línea por línea
    narrativa_turtle = turtle.Turtle()
    narrativa_turtle.penup()
    narrativa_turtle.goto(0, 200)
    for linea in lineas_narrativa:
        narrativa_turtle.write(linea, align="center", font=("Arial", 12))
        narrativa_turtle.goto(0, narrativa_turtle.ycor() - 20)  # Moverse a la siguiente línea
    narrativa_turtle.hideturtle()
    # Dibujar los espacios rectangulares
    # Espacio para dibujar
    turtle.speed(1000)
    dibujar_rectangulo(-500, 50, 1000, 350, "white")
    turtle.color("black")
    turtle.color("black")
    turtle.width(1)
    dibujo_panel(color)
    return panel

# Función para dibujar un rectángulo en la posición dada
def dibujar_rectangulo(x, y, ancho, alto, color):
    rectangulo = turtle.Turtle()
    rectangulo.penup()
    rectangulo.color(color)
    rectangulo.goto(x, y)
    rectangulo.pendown()
    rectangulo.begin_fill()
    for _ in range(2):
        rectangulo.forward(ancho)
        rectangulo.right(90)
        rectangulo.forward(alto)
        rectangulo.right(90)
    rectangulo.end_fill()
    rectangulo.hideturtle()

def dibujar_rectangulosinR(x, y, ancho, alto, color):
    rectangulo = turtle.Turtle()
    rectangulo.penup()
    rectangulo.color(color)
    rectangulo.goto(x, y)
    rectangulo.pendown()
    for _ in range(2):
        rectangulo.forward(ancho)
        rectangulo.right(90)
        rectangulo.forward(alto)
        rectangulo.right(90)
    rectangulo.hideturtle()

# funcion para dibujar un triangulo
def dibujar_triangulo(x, y, tamaño, color):
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.color(color)
    turtle.begin_fill()
    for _ in range(3):
        turtle.forward(tamaño)
        turtle.left(120)
    turtle.end_fill()

# Función para dibujar un trapecio con un color específico
def dibujar_trapecio(x, y, base1_length, base2_length, height, color):
    turtle.speed(1)
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.color(color)
    turtle.begin_fill()
    turtle.forward(base1_length)
    turtle.right(60)
    turtle.forward(height)
    turtle.right(120)
    turtle.forward(base2_length)
    turtle.right(120)
    turtle.forward(height)
    turtle.end_fill()

# Función para dibujar un rombo con un color específico
def dibujar_rombo(x, y, side_length, color):
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.color(color)
    turtle.begin_fill()
    for _ in range(2):
        turtle.forward(side_length)
        turtle.right(60)
        turtle.forward(side_length)
        turtle.right(120)
    turtle.end_fill()

# funcion para dibujar un hexagono
def dibujar_hexagono(x, y, side_length, color):
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.color(color)
    turtle.begin_fill()
    for _ in range(6):
        turtle.forward(side_length)
        turtle.right(60)
    turtle.end_fill()

# Función para dibujar un rombo con vértices horizontales
def dibujar_rombo_horizontal(x, y, lado, color):
    turtle.penup()
    turtle.goto(x, y)
    turtle.setheading(45)  # Orientar el cursor a 45 grados (hacia arriba y hacia la derecha)
    turtle.pendown()
    turtle.color(color)
    turtle.begin_fill()
    for _ in range(2):
        turtle.forward(lado)
        turtle.right(90)
        turtle.forward(lado)
        turtle.right(90)
    turtle.end_fill()  

# funcion para dibujar la primera escena  
def Dibujo1(color):

    dibujar_rectangulo(-500, 50, 1000, 350, "#87CEFA")
    dibujar_triangulo(-500,-300,375,"#228B22")
    dibujar_triangulo(-250,-300,325,"#6B8E23")
    dibujar_triangulo(100,-300,400,"green")
    dibujar_triangulo(0,-300,300,"#6B8E23")
    turtle.penup()
    turtle.goto(25,-25)
    turtle.pendown()
    turtle.color("yellow")
    turtle.begin_fill()
    turtle.circle(35)
    turtle.end_fill()
    turtle.hideturtle()
    dibujar_rombo_horizontal(-450,-50,25,"white")
    dibujar_rombo_horizontal(-425,-50,25,"white")
    dibujar_rombo_horizontal(-400,-50,25,"white")
    dibujar_rombo_horizontal(-375,-50,25,"white")
    dibujar_rombo_horizontal(-350,-50,25,"white")
    dibujar_rombo_horizontal(-325,-50,25,"white")
    dibujar_rombo_horizontal(-300,-50,25,"white")
    dibujar_rombo_horizontal(-275,-50,25,"white")
    dibujar_rombo_horizontal(-250,-50,25,"white")
    dibujar_rombo_horizontal(-225,-50,25,"white")
    dibujar_rombo_horizontal(-200,-50,25,"white")
    dibujar_rombo_horizontal(-175,-50,25,"white")
    dibujar_rombo_horizontal(-450,-40,25,"white")
    dibujar_rombo_horizontal(-425,-40,25,"white")
    dibujar_rombo_horizontal(-400,-40,25,"white")
    dibujar_rombo_horizontal(-375,-40,25,"white")
    dibujar_rombo_horizontal(-350,-40,25,"white")
    dibujar_rombo_horizontal(-325,-40,25,"white")
    dibujar_rombo_horizontal(-300,-40,25,"white")
    dibujar_rombo_horizontal(-275,-40,25,"white")
    dibujar_rombo_horizontal(-250,-40,25,"white")
    dibujar_rombo_horizontal(-225,-40,25,"white")
    dibujar_rombo_horizontal(-200,-40,25,"white")
    dibujar_rombo_horizontal(-175,-40,25,"white")
    dibujar_rectangulo(0,-200,100,100,color)
    dibujar_rectangulosinR(0,-200,100,100,"black")
    turtle.right(45)
    dibujar_rombo(0,-250,20,"white")
    dibujar_rombo(25,-250,20,"white")
    dibujar_rombo(50,-250,20,"white")
    dibujar_rombo(75,-250,20,"white")

    dibujar_rectangulo(-200,-250,200,50,"blue")
    dibujar_rectangulosinR(-200,-250,200,50,"black")
    dibujar_rectangulo(100,-250,200,50,"blue")
    dibujar_rectangulosinR(100,-250,200,50,"black")
    dibujar_rombo(-175,-275,20,"white")
    dibujar_rombo(-150,-275,20,"white")
    dibujar_rombo(-125,-275,20,"white")
    dibujar_rombo(-100,-275,20,"white")
    dibujar_rombo(-75,-275,20,"white")
    dibujar_rombo(-50,-275,20,"white")
    dibujar_rombo(100,-275,20,"white")
    dibujar_rombo(125,-275,20,"white")
    dibujar_rombo(150,-275,20,"white")
    dibujar_rombo(175,-275,20,"white")
    dibujar_rombo(200,-275,20,"white")
    dibujar_rombo(225,-275,20,"white")

# funcion para dibujar la segunda escena  
def Dibujo2(color):
        dibujar_rectangulo(-400, 25, 800, 300, "#F5F5DC")
        dibujar_rectangulosinR(-390,15,780,280,"black")
        turtle.color(color)
        turtle.penup()
        turtle.goto(-325,-225)
        turtle.pendown()
        turtle.width(10)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(150)
        turtle.right(135)
        turtle.forward(150)
        turtle.left(45)
        turtle.forward(250)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(135)
        turtle.forward(225)
        turtle.right(135)
        turtle.forward(150)
        turtle.left(90)
        dibujar_rombo(300,-225,30,"#E0115F")
        turtle.width(1)
        dibujar_triangulo(-300,-200,10,"green")
        dibujar_triangulo(-290,-200,10,"green")
        dibujar_triangulo(-280,-200,10,"green")
        dibujar_triangulo(-270,-200,10,"green")
        turtle.color("blue")
        turtle.penup()
        turtle.goto(-200,-75)
        turtle.pendown()
        turtle.begin_fill()
        turtle.circle(20)
        turtle.penup()
        turtle.goto(-175,-100)
        turtle.pendown()
        turtle.circle(20)
        turtle.penup()
        turtle.goto(-150,-125)
        turtle.pendown()
        turtle.circle(20)
        turtle.penup()
        turtle.goto(-125,-150)
        turtle.pendown()
        turtle.circle(20)
        turtle.penup()
        turtle.goto(-100,-150)
        turtle.pendown()
        turtle.circle(20)
        turtle.penup()
        turtle.goto(-75,-150)
        turtle.pendown()
        turtle.circle(20)
        turtle.end_fill()

# funcion para dibujar la tercera escena  
def Dibujo3(color):
    dibujar_rectangulo(-500, 50, 1000, 350,color)
    turtle.penup()
    turtle.goto(50,-50)
    turtle.right(90)
    dibujar_triangulo(50,-100,100,"yellow")
    dibujar_triangulo(115,-50,200,"purple")
    dibujar_triangulo(200,-100,100,"orange")
    dibujar_triangulo(115,-125,50,"green")
    turtle.left(90)
    turtle.penup()
    turtle.goto(225,-135)
    turtle.pendown()
    turtle.color("white")
    turtle.begin_fill()
    turtle.circle(10)
    turtle.end_fill()
    turtle.penup()
    turtle.right(65)
    dibujar_rombo(-375,-75,35,"black")
    dibujar_rombo(-325,-75,35,"black")
    turtle.left(65)
    dibujar_triangulo(-350,-250,100,"orange")
    dibujar_triangulo(-400,-165,100,"orange")
    turtle.penup()
    turtle.goto(-250,-250,)
    turtle.left(45)
    dibujar_trapecio(-250,-250,35,45,15,"orange")
    turtle.right(45)
    turtle.penup()
    turtle.goto(-357,-115)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color("white")
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-335,-115)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color("white")
    turtle.circle(5)
    turtle.end_fill()
    dibujar_hexagono(-365,-140,10,"brown")

# funcion para dibujar la cuarta escena  
def Dibujo4(color):
    dibujar_rectangulo(-500, 50, 1000, 350, "#87CEFA")
    dibujar_triangulo(-450,-300,375,"#228B22")
    dibujar_triangulo(-250,-300,375,"#228B22")
    dibujar_triangulo(-50,-300,375,"#228B22")
    dibujar_triangulo(100,-300,375,"#228B22")
    turtle.penup()
    turtle.goto(-450,0)
    turtle.pendown()
    turtle.color("yellow")
    turtle.begin_fill()
    turtle.circle(15)
    turtle.end_fill()
    turtle.penup()
    turtle.left(90)
    dibujar_rectangulo(-25,-200,50,100,"brown")
    dibujar_rectangulo(-75,-100,150,100,color)
    turtle.right(90)
    turtle.speed(100)
    turtle.penup()
    turtle.color("red")
    turtle.goto(-65,-180)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-50,-125)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-50,-175)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-35,-180)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-40,-130)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(65,-180)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(50,-125)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(50,-175)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(35,-180)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(40,-130)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(0,-125)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(0,-175)
    turtle.begin_fill()
    turtle.pendown()
    turtle.circle(5)
    turtle.end_fill()
    turtle.width(5)
    turtle.color(color)
    turtle.penup()
    turtle.goto(100,-275)
    turtle.pendown()
    turtle.left(30)
    turtle.forward(25)
    turtle.penup()
    turtle.goto(90,-275)
    turtle.pendown()
    turtle.left(80)
    turtle.forward(25)
    turtle.penup()
    turtle.goto(70,-275)
    turtle.pendown()
    turtle.left(30)
    turtle.forward(25)
    turtle.penup()
    turtle.goto(60,-275)
    turtle.pendown()
    turtle.left(30)
    turtle.forward(25)
    turtle.penup()
    turtle.goto(50,-275)
    turtle.pendown()
    turtle.left(30)
    turtle.forward(25)
    turtle.right(180)
    turtle.penup()
    turtle.width(1)
    dibujar_rectangulo(50,-275,50,25,"yellow")
    turtle.speed(1000)
    dibujarflor(-350,-285,color)
    dibujarflor(-325,-285,color)
    dibujarflor(-300,-285,color)
    dibujarflor(-275,-285,color)
    dibujarflor(-250,-285,color)
    dibujarflor(-225,-285,color)
    dibujarflor(-200,-285,color)
    dibujarflor(-175,-285,color)
    dibujarflor(-150,-285,color)
    dibujarflor(-125,-285,color)
    dibujarflor(-100,-285,color)
    dibujarflor(-75,-285,color)
    dibujarflor(-50,-285,color)
    dibujarflor(350,-285,color)
    dibujarflor(325,-285,color)
    dibujarflor(300,-285,color)
    dibujarflor(275,-285,color)
    dibujarflor(250,-285,color)
    dibujarflor(225,-285,color)
    dibujarflor(200,-285,color)
    dibujarflor(175,-285,color)
    dibujarflor(150,-285,color)
    dibujarflor(125,-285,color)
    turtle.speed(1000)
    dibujar_rombo_horizontal(-350,-50,25,"white")
    dibujar_rombo_horizontal(-325,-50,25,"white")
    dibujar_rombo_horizontal(-300,-50,25,"white")
    dibujar_rombo_horizontal(-275,-50,25,"white")
    dibujar_rombo_horizontal(-250,-50,25,"white")
    dibujar_rombo_horizontal(-225,-50,25,"white")
    dibujar_rombo_horizontal(-200,-50,25,"white")
    dibujar_rombo_horizontal(-175,-50,25,"white")
    dibujar_rombo_horizontal(-150,-50,25,"white")
    dibujar_rombo_horizontal(-125,-50,25,"white")
    dibujar_rombo_horizontal(-100,-50,25,"white")
    dibujar_rombo_horizontal(-75,-50,25,"white")
    dibujar_rombo_horizontal(-50,-50,25,"white")
    dibujar_rombo_horizontal(-25,-50,25,"white")
    dibujar_rombo_horizontal(-0,-50,25,"white")
    dibujar_rombo_horizontal(-350,-40,25,"white")
    dibujar_rombo_horizontal(-325,-40,25,"white")
    dibujar_rombo_horizontal(-300,-40,25,"white")
    dibujar_rombo_horizontal(-275,-40,25,"white")
    dibujar_rombo_horizontal(-250,-40,25,"white")
    dibujar_rombo_horizontal(-225,-40,25,"white")
    dibujar_rombo_horizontal(-200,-40,25,"white")
    dibujar_rombo_horizontal(-175,-40,25,"white")
    dibujar_rombo_horizontal(-150,-40,25,"white")
    dibujar_rombo_horizontal(-125,-40,25,"white")
    dibujar_rombo_horizontal(-100,-40,25,"white")
    dibujar_rombo_horizontal(-75,-40,25,"white")
    dibujar_rombo_horizontal(-50,-40,25,"white")
    dibujar_rombo_horizontal(-25,-40,25,"white")
    dibujar_rombo_horizontal(-0,-40,25,"white")
    dibujar_rombo_horizontal(350,-50,25,"white")
    dibujar_rombo_horizontal(325,-50,25,"white")
    dibujar_rombo_horizontal(300,-50,25,"white")
    dibujar_rombo_horizontal(275,-50,25,"white")
    dibujar_rombo_horizontal(250,-50,25,"white")
    dibujar_rombo_horizontal(225,-50,25,"white")
    dibujar_rombo_horizontal(200,-50,25,"white")
    dibujar_rombo_horizontal(175,-50,25,"white")
    dibujar_rombo_horizontal(150,-50,25,"white")
    dibujar_rombo_horizontal(125,-50,25,"white")
    dibujar_rombo_horizontal(100,-50,25,"white")
    dibujar_rombo_horizontal(75,-50,25,"white")
    dibujar_rombo_horizontal(50,-50,25,"white")
    dibujar_rombo_horizontal(25,-50,25,"white")
    dibujar_rombo_horizontal(0,-50,25,"white")
    dibujar_rombo_horizontal(350,-40,25,"white")
    dibujar_rombo_horizontal(325,-40,25,"white")
    dibujar_rombo_horizontal(300,-40,25,"white")
    dibujar_rombo_horizontal(275,-40,25,"white")
    dibujar_rombo_horizontal(250,-40,25,"white")
    dibujar_rombo_horizontal(225,-40,25,"white")
    dibujar_rombo_horizontal(200,-40,25,"white")
    dibujar_rombo_horizontal(175,-40,25,"white")
    dibujar_rombo_horizontal(150,-40,25,"white")
    dibujar_rombo_horizontal(125,-40,25,"white")
    dibujar_rombo_horizontal(100,-40,25,"white")
    dibujar_rombo_horizontal(75,-40,25,"white")
    dibujar_rombo_horizontal(50,-40,25,"white")
    dibujar_rombo_horizontal(25,-40,25,"white")
    dibujar_rombo_horizontal(0,-40,25,"white")

# funcion para dibujar la quitna escena  
def Dibujo5(color):
    dibujar_rectangulo(-500, 50, 1000, 350, "#87CEFA")
    dibujar_triangulo(-450,-300,375,"#228B22")
    dibujar_triangulo(-250,-300,375,"#228B22")
    dibujar_triangulo(-50,-300,375,"#228B22")
    dibujar_triangulo(-300,-300,150,color)
    dibujar_triangulo(-200,-300,150,"blue")
    dibujar_triangulo(-100,-300,150,color)
    dibujar_triangulo(-0,-300,150,"blue")
    dibujar_triangulo(100,-300,150,color)
    dibujar_triangulo(200,-300,150,"blue")
    turtle.penup()
    turtle.goto(-225,-200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color("#FFE4C4")
    turtle.circle(30)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-125,-200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color("#FFE4C4")
    turtle.circle(30)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-25,-200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color("#8B7E66")
    turtle.circle(30)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(75,-200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color("#8B7E66")
    turtle.circle(30)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(175,-200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color("#FFE4C4")
    turtle.circle(30)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(275,-200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color("#FFE4C4")
    turtle.circle(30)
    turtle.end_fill()
    turtle.penup()
    turtle.right(65)
    dibujar_rombo(-475,-125,35,"black")
    dibujar_rombo(-425,-125,35,"black")
    turtle.left(65)
    dibujar_triangulo(-450,-300,100,"orange")
    dibujar_triangulo(-500,-205,100,"orange")
    turtle.penup()
    turtle.goto(-350,-300,)
    turtle.left(45)
    dibujar_trapecio(-350,-300,35,45,15,"orange")
    turtle.right(45)
    turtle.penup()
    turtle.goto(-457,-165)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color("white")
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-435,-165)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color("white")
    turtle.circle(5)
    turtle.end_fill()
    dibujar_hexagono(-465,-190,10,"brown")
    turtle.penup()
    turtle.goto(-425,0)
    turtle.pendown()
    turtle.color("yellow")
    turtle.begin_fill()
    turtle.circle(30)
    turtle.end_fill()
    turtle.penup()


# funcion para dibujar la escena final  
def DibujoF(color):
        dibujar_rectangulo(-500, 50, 1000, 350, color)

# funcion para dibujar una flor
def dibujarflor(x,y,color):
    turtle.penup()
    turtle.goto(x,y)
    dibujar_rectangulo(x,y,10,15,"#00FF00")
    turtle.color(color)
    turtle.penup()
    turtle.goto((x+7.5),y)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(5)
    turtle.end_fill()
    turtle.penup()

# Agregar valor verdadero, para pasar de paneles
def EvaluarCorrecto(correcto):
    while True:
        respuesta = input("Ingresa el numero de tu respuesta")
        if respuesta.isdigit():  
            if int(respuesta) == int(correcto):
                print("Felicidades, respuesta correcta")
                return
            else:
                print()
                print("Respuesta incorrecta intenta de nuevo")
        else:
            print()
            print("La respuesta debe ser número entero. Por favor, inténtalo de nuevo.")
def main():
    nombre = pedir_nombre()
    edad = pedir_edad()
    color = pedir_color() 

    titulo = "El Comienzo"
    titulo2 = "La Partida"
    titulo3 = "Los Desafíos"
    titulo4 = "El Descubrimiento"
    titulo5 = "El Regreso"

# El cuento
    narrativa = f"Había una vez en un pequeño pueblo llamado Villa Feliz, un niño llamado {nombre}. Tenía {edad} años y siempre soñaba con vivir grandes aventuras. Un día, {nombre} decidió que era hora de emprender un viaje emocionante para descubrir el mundo más allá de las colinas que rodeaban su hogar."
    narrativa2 = f"Con una mochila llena de provisiones y un corazón lleno de valentía, {nombre} se despidió de sus padres y amigos. Con un nudo en la garganta pero una sonrisa en el rostro, comenzó su viaje hacia lo desconocido. Por el camino, {nombre} se encontró con un viejo sabio que le dio un mapa misterioso y le dijo: Este mapa te guiará hacia tu destino, pero recuerda que el verdadero tesoro está en el camino"
    narrativa3 = f"{nombre} se adentró en el bosque espeso, enfrentando desafíos como ríos caudalosos y montañas imponentes. Con ingenio y determinación, superó cada obstáculo que se interpuso en su camino. En su travesía, {nombre} conoció a nuevos amigos como el simpático perro Zippy y el pez Coco, quienes lo ayudaron a sortear las dificultades del camino."
    narrativa4 = f"Tras días de caminar y explorar, {nombre} finalmente llegó a un valle oculto donde descubrió un jardín mágico lleno de flores de todos los colores y tamaños. En el centro del jardín, había un árbol gigante con ramas que parecían tocar el cielo. Bajo la sombra del árbol, {nombre} encontró un cofre brillante que contenía el tesoro más valioso de todos: la amistad, la valentía y la sabiduría."
    narrativa5 = f"Con el tesoro en su corazón y el mapa en la mano, {nombre} emprendió el regreso a Villa Feliz. Esta vez, el viaje se sintió más corto y ligero, ya que {nombre} sabía que no importaba cuán lejos viajara, siempre tendría un hogar en su corazón y amigos que lo esperaban con los brazos abiertos. Al llegar a casa, {nombre} compartió sus aventuras con su familia y amigos, inspirándolos a ellos también a seguir sus propios sueños y aventuras."
   

    panel = dibujar_panel(titulo, narrativa,Dibujo1,color)

# Pregunta para pasar al segundo panel 
    print()
    print()
    print()
    print("Pregunta Panel 1: ")
    print(f"¿Cómo se llama el pueblo donde vive {nombre}?")
    print("1. Villa Triste")
    print("2. Villa Feliz")
    print("3. Villa Encantada")
    print()
    EvaluarCorrecto(2)
    print()
    panel.clear()

# Pregunta para pasar al panel 3 
    panel = dibujar_panel(titulo2, narrativa2,Dibujo2,color)
    print()
    print()
    print()
    print("Pregunta Panel 2: ")
    print(f"¿Quién le dio a {nombre} un mapa misterioso para su viaje?")
    print("1. Un hada")
    print("2. Un mago")
    print("3. Un anciano sabio")
    print()
    EvaluarCorrecto(3)
    print()
    panel.clear()

#Preguta para pasar al panel 4
    panel = dibujar_panel(titulo3,narrativa3,Dibujo3,color)
    print()
    print()
    print()
    print("Pregunta Panel 3: ")
    print(f"¿Quiénes son los nuevos amigos que {nombre} conoce en su viaje?")
    print("1. Zippy y Coco")
    print("2. Benny y Lulu")
    print("3. Sparky y Twinkle")
    print()
    EvaluarCorrecto(1)
    print()
    panel.clear()

#Panel para pasar a panel 5 
    panel=dibujar_panel(titulo4,narrativa4,Dibujo4,color)
    print()
    print()
    print()
    print("Pregunta Panel 4: ")
    print(f"¿Qué encontró {nombre} en el valle oculto?")
    print("1. Un cofre brillante")
    print("2. Una puerta Mágica")
    print("3. Un castillo encantado")
    print()
    EvaluarCorrecto(1)
    print()
    panel.clear()

#Para terminar 
    panel=dibujar_panel(titulo5,narrativa5,Dibujo5,color)
    print()
    print()
    print()
    print("Pregunta Panel 5: ")
    print(f"¿Qué compartió {nombre} con su familia y amigos al regresar a casa?")
    print("1. Un tesoso de oro")
    print("2. Un mapa antiguo")
    print("3. Sus aventuras")
    print()
    EvaluarCorrecto(3)
    print()
    panel.clear()
    panel=dibujar_panel("FELICIDADES COMPLETASTE EL CUENTO","",DibujoF,color)

    panel.mainloop()

if __name__ == "__main__":
    main()